/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API de recordatorios de medicamentos
 * Contrato de la API. Fuente de verdad del backend y de los clientes generados por el frontend
 * (Orval para la web, openapi-generator para el reloj Wear OS).
 *
 * Convenciones:
 * - Rutas en kebab-case y plural; campos JSON en camelCase; fechas ISO 8601 con zona; IDs UUID.
 * - Errores en RFC 9457 (`application/problem+json`) con `type`, `title`, `status`, `detail`, `code`.
 * - Paginación por cursor (`?cursor=&limit=`) con respuesta `{ items, nextCursor }`.
 *
 * Autenticación (`Authorization: Bearer <accessToken>`, JWT de 15 min). Hay dos tipos de sesión:
 * - **Usuario (web)**: se abre con `POST /auth/register` o `POST /auth/login` y se renueva con
 *   `POST /auth/refresh`. El token de acceso va en el JSON; el **refresh token nunca va en el
 *   JSON**: viaja solo en la cookie `__Secure-refresh-token` (`HttpOnly; Secure;
 *   SameSite=Strict; Path=/auth; Max-Age=2592000`). El navegador la envía sola a `/auth/*`; la
 *   web debe llamar con `credentials: "include"`. CORS con credenciales solo para el origen del
 *   panel web. `POST /auth/logout` la borra (`Max-Age=0`). Su token de acceso no sirve en
 *   `/devices/me/*` (403).
 * - **Reloj**: se abre con `POST /devices/token` (`grantType: device_code`) y se renueva con el
 *   mismo endpoint (`grantType: refresh_token`). Recibe **ambos tokens en JSON** (no usa
 *   cookies). Su token **solo** sirve en `/devices/me/*`; en cualquier otra ruta responde 403.
 *   `POST /auth/refresh` rechaza refresh tokens de reloj (401).
 * En ambos casos el refresh token es rotativo: cada uso devuelve uno nuevo e invalida el anterior;
 * reutilizar uno ya rotado revoca toda la familia (`code: refresh_token_reused`). El refresh token
 * de usuario caduca a los 30 días; el del reloj, tras 90 días sin uso. Desvincular un reloj
 * revoca sus tokens.
 *
 * Pacientes y cuidadores:
 * - Al registrarse con `role: patient` se crea automáticamente su registro en `/patients`
 *   (`managed: false`, mismo `displayName` y `timezone`) y `user.patientId` apunta a él. Ese
 *   paciente puede invitar cuidadores y gestiona sus propios consentimientos.
 * - Un cuidador puede crear pacientes gestionados (`managed: true`, sin cuenta propia) con
 *   `POST /patients`; otorga sus consentimientos en su nombre y queda registrado en `grantedBy`.
 * - Cualquier ruta `/patients/{patientId}/...` sobre un paciente con el que el usuario no tiene
 *   un vínculo activo responde **404** (no 403), para no revelar que existe. 403 se reserva a
 *   acciones sobre un paciente accesible que el rol no permite.
 *
 * Códigos de un solo uso (invitación de cuidador y vinculación del reloj): caducan, se consumen
 * al usarse y tienen límite de intentos por usuario/IP; al superarlo responden 429 con
 * `Retry-After`.
 *
 * Cada operación lleva `x-phase` (fase en que se implementa). `info.x-closed-phase` es la última
 * fase cerrada: todas sus operaciones deben estar implementadas.
 *
 * Fases:
 * - 0 Fundaciones: salud.
 * - 1 Cuentas y vinculación: registro, sesión, perfil, consentimientos, pacientes, cuidadores
 *   y vinculación del reloj por código (flujo tipo device code, RFC 8628).
 * - 2 Sprint A (plan exprés, fases 2 y 3 juntas): medicamentos, horarios simples (horas del día,
 *   días de la semana, fechas de inicio y fin; sin RRULE), plan de 7 días versionado, eventos
 *   de toma idempotentes, historial y adherencia. `MISSED` se calcula al consultar.
 * - 3 Sprint B (plan exprés, fases 4 y 5 juntas): verificación de correo y recuperación de
 *   contraseña, canales y preferencias de notificación (Telegram y correo), reportes semanales
 *   en PDF y chat con IA (SSE para la web, respuesta corta para el reloj). El envío de avisos
 *   (alerta de dosis omitida, reporte semanal) lo hace un worker en segundo plano: no hay
 *   endpoint para dispararlos.
 *
 * OpenAPI spec version: 0.5.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  ConsentPurpose,
  DoseStatus,
  Locale,
  NotificationChannelType,
  ReportStatus,
  ReportTrigger,
  Role
} from './generated';
import type {
  AccessToken,
  Adherence,
  AuthSession,
  CareLink,
  CareLinkPage,
  CaregiverInvitation,
  Consent,
  ConsentActor,
  ConsentList,
  Device,
  DevicePage,
  DoseEventBatchResult,
  DoseHistoryPage,
  Health,
  Medication,
  MedicationPage,
  NotificationChannelList,
  NotificationPreferences,
  PairingCode,
  Patient,
  PatientPage,
  Plan,
  Readiness,
  Report,
  ReportPage,
  ReportSummary,
  Schedule,
  ScheduleList,
  TelegramLink,
  TokenPair,
  User,
  WatchChatReply
} from './generated';


export const getGetHealthResponseMock = (overrideResponse: Partial<Extract<Health, object>> = {}): Health => ({status: faker.helpers.arrayElement(['ok'] as const), ...overrideResponse})

export const getGetReadinessResponseMock = (overrideResponse: Partial<Extract<Readiness, object>> = {}): Readiness => ({status: faker.helpers.arrayElement(['ok'] as const), checks: {database: faker.helpers.arrayElement(['ok'] as const), redis: faker.helpers.arrayElement(['ok'] as const)}, ...overrideResponse})

export const getRegisterResponseMock = (overrideResponse: Partial<Extract<AuthSession, object>> = {}): AuthSession => ({user: {id: faker.string.uuid(), email: faker.internet.email(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), role: faker.helpers.arrayElement(Object.values(Role)), timezone: faker.string.alpha({length: {min: 1, max: 64}}), locale: faker.helpers.arrayElement(Object.values(Locale)), patientId: faker.helpers.arrayElement([faker.string.uuid(),null,]), emailVerified: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z'}, tokens: {accessToken: faker.string.alpha({length: {min: 10, max: 20}}), tokenType: faker.helpers.arrayElement(['Bearer'] as const), expiresIn: faker.number.int()}, ...overrideResponse})

export const getLoginResponseMock = (overrideResponse: Partial<Extract<AuthSession, object>> = {}): AuthSession => ({user: {id: faker.string.uuid(), email: faker.internet.email(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), role: faker.helpers.arrayElement(Object.values(Role)), timezone: faker.string.alpha({length: {min: 1, max: 64}}), locale: faker.helpers.arrayElement(Object.values(Locale)), patientId: faker.helpers.arrayElement([faker.string.uuid(),null,]), emailVerified: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z'}, tokens: {accessToken: faker.string.alpha({length: {min: 10, max: 20}}), tokenType: faker.helpers.arrayElement(['Bearer'] as const), expiresIn: faker.number.int()}, ...overrideResponse})

export const getRefreshTokensResponseMock = (overrideResponse: Partial<Extract<AccessToken, object>> = {}): AccessToken => ({accessToken: faker.string.alpha({length: {min: 10, max: 20}}), tokenType: faker.helpers.arrayElement(['Bearer'] as const), expiresIn: faker.number.int(), ...overrideResponse})

export const getGetMeResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({id: faker.string.uuid(), email: faker.internet.email(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), role: faker.helpers.arrayElement(Object.values(Role)), timezone: faker.string.alpha({length: {min: 1, max: 64}}), locale: faker.helpers.arrayElement(Object.values(Locale)), patientId: faker.helpers.arrayElement([faker.string.uuid(),null,]), emailVerified: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateMeResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({id: faker.string.uuid(), email: faker.internet.email(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), role: faker.helpers.arrayElement(Object.values(Role)), timezone: faker.string.alpha({length: {min: 1, max: 64}}), locale: faker.helpers.arrayElement(Object.values(Locale)), patientId: faker.helpers.arrayElement([faker.string.uuid(),null,]), emailVerified: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getListMyConsentsResponseConsentActorMock = (overrideResponse: Partial<ConsentActor> = {}): ConsentActor => ({...{userId: faker.string.uuid(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), onBehalf: faker.datatype.boolean()}, ...overrideResponse});

export const getListMyConsentsResponseMock = (overrideResponse: Partial<Extract<ConsentList, object>> = {}): ConsentList => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({purpose: faker.helpers.arrayElement(Object.values(ConsentPurpose)), granted: faker.datatype.boolean(), version: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), grantedBy: faker.helpers.arrayElement([{...getListMyConsentsResponseConsentActorMock()},null,])})), ...overrideResponse})

export const getSetMyConsentResponseConsentActorMock = (overrideResponse: Partial<ConsentActor> = {}): ConsentActor => ({...{userId: faker.string.uuid(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), onBehalf: faker.datatype.boolean()}, ...overrideResponse});

export const getSetMyConsentResponseMock = (overrideResponse: Partial<Extract<Consent, object>> = {}): Consent => ({purpose: faker.helpers.arrayElement(Object.values(ConsentPurpose)), granted: faker.datatype.boolean(), version: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), grantedBy: faker.helpers.arrayElement([{...getSetMyConsentResponseConsentActorMock()},null,]), ...overrideResponse})

export const getListPatientsResponseMock = (overrideResponse: Partial<Extract<PatientPage, object>> = {}): PatientPage => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), timezone: faker.string.alpha({length: {min: 1, max: 64}}), managed: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z'})), nextCursor: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), ...overrideResponse})

export const getCreatePatientResponseMock = (overrideResponse: Partial<Extract<Patient, object>> = {}): Patient => ({id: faker.string.uuid(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), timezone: faker.string.alpha({length: {min: 1, max: 64}}), managed: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetPatientResponseMock = (overrideResponse: Partial<Extract<Patient, object>> = {}): Patient => ({id: faker.string.uuid(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), timezone: faker.string.alpha({length: {min: 1, max: 64}}), managed: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdatePatientResponseMock = (overrideResponse: Partial<Extract<Patient, object>> = {}): Patient => ({id: faker.string.uuid(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), timezone: faker.string.alpha({length: {min: 1, max: 64}}), managed: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getListPatientConsentsResponseConsentActorMock = (overrideResponse: Partial<ConsentActor> = {}): ConsentActor => ({...{userId: faker.string.uuid(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), onBehalf: faker.datatype.boolean()}, ...overrideResponse});

export const getListPatientConsentsResponseMock = (overrideResponse: Partial<Extract<ConsentList, object>> = {}): ConsentList => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({purpose: faker.helpers.arrayElement(Object.values(ConsentPurpose)), granted: faker.datatype.boolean(), version: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), grantedBy: faker.helpers.arrayElement([{...getListPatientConsentsResponseConsentActorMock()},null,])})), ...overrideResponse})

export const getSetPatientConsentResponseConsentActorMock = (overrideResponse: Partial<ConsentActor> = {}): ConsentActor => ({...{userId: faker.string.uuid(), displayName: faker.string.alpha({length: {min: 1, max: 80}}), onBehalf: faker.datatype.boolean()}, ...overrideResponse});

export const getSetPatientConsentResponseMock = (overrideResponse: Partial<Extract<Consent, object>> = {}): Consent => ({purpose: faker.helpers.arrayElement(Object.values(ConsentPurpose)), granted: faker.datatype.boolean(), version: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), updatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), grantedBy: faker.helpers.arrayElement([{...getSetPatientConsentResponseConsentActorMock()},null,]), ...overrideResponse})

export const getListPatientCaregiversResponseMock = (overrideResponse: Partial<Extract<CareLinkPage, object>> = {}): CareLinkPage => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({patientId: faker.string.uuid(), caregiverId: faker.string.uuid(), caregiverDisplayName: faker.string.alpha({length: {min: 1, max: 80}}), active: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z'})), nextCursor: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), ...overrideResponse})

export const getCreateCaregiverInvitationResponseMock = (overrideResponse: Partial<Extract<CaregiverInvitation, object>> = {}): CaregiverInvitation => ({code: faker.helpers.fromRegExp("^[A-HJKMNP-Z2-9]{10}$"), patientId: faker.string.uuid(), expiresAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getAcceptCaregiverInvitationResponseMock = (overrideResponse: Partial<Extract<CareLink, object>> = {}): CareLink => ({patientId: faker.string.uuid(), caregiverId: faker.string.uuid(), caregiverDisplayName: faker.string.alpha({length: {min: 1, max: 80}}), active: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getCreatePairingCodeResponseMock = (overrideResponse: Partial<Extract<PairingCode, object>> = {}): PairingCode => ({code: faker.helpers.fromRegExp("^[BCDFGHJKLMNPQRSTVWXZ]{4}-[BCDFGHJKLMNPQRSTVWXZ]{4}$"), deviceCode: faker.string.alpha({length: {min: 10, max: 20}}), expiresIn: faker.number.int(), interval: faker.number.int(), ...overrideResponse})

export const getConfirmPairingCodeResponseMock = (overrideResponse: Partial<Extract<Device, object>> = {}): Device => ({id: faker.string.uuid(), patientId: faker.string.uuid(), model: faker.string.alpha({length: {min: 10, max: 20}}), pairedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', lastSeenAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), hasPushToken: faker.datatype.boolean(), ...overrideResponse})

export const getRequestDeviceTokenResponseMock = (overrideResponse: Partial<Extract<TokenPair, object>> = {}): TokenPair => ({accessToken: faker.string.alpha({length: {min: 10, max: 20}}), refreshToken: faker.string.alpha({length: {min: 10, max: 20}}), tokenType: faker.helpers.arrayElement(['Bearer'] as const), expiresIn: faker.number.int(), ...overrideResponse})

export const getGetMyDeviceResponseMock = (overrideResponse: Partial<Extract<Device, object>> = {}): Device => ({id: faker.string.uuid(), patientId: faker.string.uuid(), model: faker.string.alpha({length: {min: 10, max: 20}}), pairedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', lastSeenAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), hasPushToken: faker.datatype.boolean(), ...overrideResponse})

export const getListPatientDevicesResponseMock = (overrideResponse: Partial<Extract<DevicePage, object>> = {}): DevicePage => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), patientId: faker.string.uuid(), model: faker.string.alpha({length: {min: 10, max: 20}}), pairedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', lastSeenAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), hasPushToken: faker.datatype.boolean()})), nextCursor: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), ...overrideResponse})

export const getListMedicationsResponseMock = (overrideResponse: Partial<Extract<MedicationPage, object>> = {}): MedicationPage => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), patientId: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), dosage: faker.string.alpha({length: {min: 10, max: 20}}), instructions: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), color: faker.helpers.fromRegExp("^#[0-9A-Fa-f]{6}$"), archived: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z'})), nextCursor: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), ...overrideResponse})

export const getCreateMedicationResponseMock = (overrideResponse: Partial<Extract<Medication, object>> = {}): Medication => ({id: faker.string.uuid(), patientId: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), dosage: faker.string.alpha({length: {min: 10, max: 20}}), instructions: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), color: faker.helpers.fromRegExp("^#[0-9A-Fa-f]{6}$"), archived: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetMedicationResponseMock = (overrideResponse: Partial<Extract<Medication, object>> = {}): Medication => ({id: faker.string.uuid(), patientId: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), dosage: faker.string.alpha({length: {min: 10, max: 20}}), instructions: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), color: faker.helpers.fromRegExp("^#[0-9A-Fa-f]{6}$"), archived: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateMedicationResponseMock = (overrideResponse: Partial<Extract<Medication, object>> = {}): Medication => ({id: faker.string.uuid(), patientId: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), dosage: faker.string.alpha({length: {min: 10, max: 20}}), instructions: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), color: faker.helpers.fromRegExp("^#[0-9A-Fa-f]{6}$"), archived: faker.datatype.boolean(), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', updatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getListSchedulesResponseMock = (overrideResponse: Partial<Extract<ScheduleList, object>> = {}): ScheduleList => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), medicationId: faker.string.uuid(), times: Array.from({ length: faker.number.int({min: 1, max: 12}) }, (_, i) => i + 1).map(() => (faker.helpers.fromRegExp("^([01][0-9]|2[0-3]):[0-5][0-9]$"))), daysOfWeek: Array.from({ length: faker.number.int({min: 1, max: 7}) }, (_, i) => i + 1).map(() => (faker.number.int({min: 1, max: 7}))), startDate: faker.date.past().toISOString().slice(0, 10), endDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10),null,])})), ...overrideResponse})

export const getCreateScheduleResponseMock = (overrideResponse: Partial<Extract<Schedule, object>> = {}): Schedule => ({id: faker.string.uuid(), medicationId: faker.string.uuid(), times: Array.from({ length: faker.number.int({min: 1, max: 12}) }, (_, i) => i + 1).map(() => (faker.helpers.fromRegExp("^([01][0-9]|2[0-3]):[0-5][0-9]$"))), daysOfWeek: Array.from({ length: faker.number.int({min: 1, max: 7}) }, (_, i) => i + 1).map(() => (faker.number.int({min: 1, max: 7}))), startDate: faker.date.past().toISOString().slice(0, 10), endDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10),null,]), ...overrideResponse})

export const getUpdateScheduleResponseMock = (overrideResponse: Partial<Extract<Schedule, object>> = {}): Schedule => ({id: faker.string.uuid(), medicationId: faker.string.uuid(), times: Array.from({ length: faker.number.int({min: 1, max: 12}) }, (_, i) => i + 1).map(() => (faker.helpers.fromRegExp("^([01][0-9]|2[0-3]):[0-5][0-9]$"))), daysOfWeek: Array.from({ length: faker.number.int({min: 1, max: 7}) }, (_, i) => i + 1).map(() => (faker.number.int({min: 1, max: 7}))), startDate: faker.date.past().toISOString().slice(0, 10), endDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10),null,]), ...overrideResponse})

export const getGetMyPlanResponseMock = (overrideResponse: Partial<Extract<Plan, object>> = {}): Plan => ({version: faker.number.int({min: 0}), patientTimezone: faker.string.alpha({length: {min: 1, max: 64}}), generatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', validFrom: faker.date.past().toISOString().slice(0, 19) + 'Z', validUntil: faker.date.past().toISOString().slice(0, 19) + 'Z', doses: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({scheduleId: faker.string.uuid(), medicationId: faker.string.uuid(), medicationName: faker.string.alpha({length: {min: 10, max: 20}}), dosage: faker.string.alpha({length: {min: 10, max: 20}}), instructions: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), color: faker.helpers.fromRegExp("^#[0-9A-Fa-f]{6}$"), scheduledAt: faker.date.past().toISOString().slice(0, 19) + 'Z'})), ...overrideResponse})

export const getGetPatientPlanResponseMock = (overrideResponse: Partial<Extract<Plan, object>> = {}): Plan => ({version: faker.number.int({min: 0}), patientTimezone: faker.string.alpha({length: {min: 1, max: 64}}), generatedAt: faker.date.past().toISOString().slice(0, 19) + 'Z', validFrom: faker.date.past().toISOString().slice(0, 19) + 'Z', validUntil: faker.date.past().toISOString().slice(0, 19) + 'Z', doses: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({scheduleId: faker.string.uuid(), medicationId: faker.string.uuid(), medicationName: faker.string.alpha({length: {min: 10, max: 20}}), dosage: faker.string.alpha({length: {min: 10, max: 20}}), instructions: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), color: faker.helpers.fromRegExp("^#[0-9A-Fa-f]{6}$"), scheduledAt: faker.date.past().toISOString().slice(0, 19) + 'Z'})), ...overrideResponse})

export const getCreateMyDoseEventsResponseMock = (overrideResponse: Partial<Extract<DoseEventBatchResult, object>> = {}): DoseEventBatchResult => ({results: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({eventId: faker.string.uuid(), outcome: faker.helpers.arrayElement(['created','duplicate','rejected'] as const), code: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null])})), ...overrideResponse})

export const getListDoseHistoryResponseMock = (overrideResponse: Partial<Extract<DoseHistoryPage, object>> = {}): DoseHistoryPage => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({scheduleId: faker.string.uuid(), medicationId: faker.string.uuid(), medicationName: faker.string.alpha({length: {min: 10, max: 20}}), dosage: faker.string.alpha({length: {min: 10, max: 20}}), scheduledAt: faker.date.past().toISOString().slice(0, 19) + 'Z', status: faker.helpers.arrayElement(Object.values(DoseStatus)), actedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,])})), nextCursor: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), ...overrideResponse})

export const getGetAdherenceResponseMock = (overrideResponse: Partial<Extract<Adherence, object>> = {}): Adherence => ({from: faker.date.past().toISOString().slice(0, 10), to: faker.date.past().toISOString().slice(0, 10), taken: faker.number.int({min: 0}), skipped: faker.number.int({min: 0}), missed: faker.number.int({min: 0}), percentage: faker.helpers.arrayElement([faker.number.float({min: 0, max: 100, fractionDigits: 2}),null,]), ...overrideResponse})

export const getListMyNotificationChannelsResponseMock = (overrideResponse: Partial<Extract<NotificationChannelList, object>> = {}): NotificationChannelList => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({channel: faker.helpers.arrayElement(Object.values(NotificationChannelType)), linked: faker.datatype.boolean(), verified: faker.datatype.boolean(), label: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), linkedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,])})), ...overrideResponse})

export const getCreateTelegramLinkResponseMock = (overrideResponse: Partial<Extract<TelegramLink, object>> = {}): TelegramLink => ({url: faker.internet.url(), expiresAt: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetMyNotificationPreferencesResponseMock = (overrideResponse: Partial<Extract<NotificationPreferences, object>> = {}): NotificationPreferences => ({missedDose: {...{email: faker.datatype.boolean(), telegram: faker.datatype.boolean()},}, weeklyReport: {...{email: faker.datatype.boolean(), telegram: faker.datatype.boolean()},}, ...overrideResponse})

export const getSetMyNotificationPreferencesResponseMock = (overrideResponse: Partial<Extract<NotificationPreferences, object>> = {}): NotificationPreferences => ({missedDose: {...{email: faker.datatype.boolean(), telegram: faker.datatype.boolean()},}, weeklyReport: {...{email: faker.datatype.boolean(), telegram: faker.datatype.boolean()},}, ...overrideResponse})

export const getListReportsResponseReportSummaryMock = (overrideResponse: Partial<ReportSummary> = {}): ReportSummary => ({...{taken: faker.number.int({min: 0}), skipped: faker.number.int({min: 0}), missed: faker.number.int({min: 0}), percentage: faker.helpers.arrayElement([faker.number.float({min: 0, max: 100, fractionDigits: 2}),null,]), byMedication: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({medicationId: faker.string.uuid(), medicationName: faker.string.alpha({length: {min: 10, max: 20}}), taken: faker.number.int({min: 0}), skipped: faker.number.int({min: 0}), missed: faker.number.int({min: 0}), percentage: faker.helpers.arrayElement([faker.number.float({min: 0, max: 100, fractionDigits: 2}),null,])}))}, ...overrideResponse});

export const getListReportsResponseMock = (overrideResponse: Partial<Extract<ReportPage, object>> = {}): ReportPage => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), patientId: faker.string.uuid(), periodStart: faker.date.past().toISOString().slice(0, 10), periodEnd: faker.date.past().toISOString().slice(0, 10), trigger: faker.helpers.arrayElement(Object.values(ReportTrigger)), status: faker.helpers.arrayElement(Object.values(ReportStatus)), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', generatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), summary: faker.helpers.arrayElement([{...getListReportsResponseReportSummaryMock()},null,])})), nextCursor: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), ...overrideResponse})

export const getCreateReportResponseReportSummaryMock = (overrideResponse: Partial<ReportSummary> = {}): ReportSummary => ({...{taken: faker.number.int({min: 0}), skipped: faker.number.int({min: 0}), missed: faker.number.int({min: 0}), percentage: faker.helpers.arrayElement([faker.number.float({min: 0, max: 100, fractionDigits: 2}),null,]), byMedication: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({medicationId: faker.string.uuid(), medicationName: faker.string.alpha({length: {min: 10, max: 20}}), taken: faker.number.int({min: 0}), skipped: faker.number.int({min: 0}), missed: faker.number.int({min: 0}), percentage: faker.helpers.arrayElement([faker.number.float({min: 0, max: 100, fractionDigits: 2}),null,])}))}, ...overrideResponse});

export const getCreateReportResponseMock = (overrideResponse: Partial<Extract<Report, object>> = {}): Report => ({id: faker.string.uuid(), patientId: faker.string.uuid(), periodStart: faker.date.past().toISOString().slice(0, 10), periodEnd: faker.date.past().toISOString().slice(0, 10), trigger: faker.helpers.arrayElement(Object.values(ReportTrigger)), status: faker.helpers.arrayElement(Object.values(ReportStatus)), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', generatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), summary: faker.helpers.arrayElement([{...getCreateReportResponseReportSummaryMock()},null,]), ...overrideResponse})

export const getGetReportResponseReportSummaryMock = (overrideResponse: Partial<ReportSummary> = {}): ReportSummary => ({...{taken: faker.number.int({min: 0}), skipped: faker.number.int({min: 0}), missed: faker.number.int({min: 0}), percentage: faker.helpers.arrayElement([faker.number.float({min: 0, max: 100, fractionDigits: 2}),null,]), byMedication: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({medicationId: faker.string.uuid(), medicationName: faker.string.alpha({length: {min: 10, max: 20}}), taken: faker.number.int({min: 0}), skipped: faker.number.int({min: 0}), missed: faker.number.int({min: 0}), percentage: faker.helpers.arrayElement([faker.number.float({min: 0, max: 100, fractionDigits: 2}),null,])}))}, ...overrideResponse});

export const getGetReportResponseMock = (overrideResponse: Partial<Extract<Report, object>> = {}): Report => ({id: faker.string.uuid(), patientId: faker.string.uuid(), periodStart: faker.date.past().toISOString().slice(0, 10), periodEnd: faker.date.past().toISOString().slice(0, 10), trigger: faker.helpers.arrayElement(Object.values(ReportTrigger)), status: faker.helpers.arrayElement(Object.values(ReportStatus)), createdAt: faker.date.past().toISOString().slice(0, 19) + 'Z', generatedAt: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z',null,]), summary: faker.helpers.arrayElement([{...getGetReportResponseReportSummaryMock()},null,]), ...overrideResponse})

export const getDownloadReportPdfResponseMock = (): Blob => (new Blob([new Uint8Array(faker.number.int({ min: 1, max: 64 }))]))

export const getSendChatMessageResponseMock = (): string => (faker.word.sample())

export const getSendMyChatMessageResponseMock = (overrideResponse: Partial<Extract<WatchChatReply, object>> = {}): WatchChatReply => ({reply: faker.string.alpha({length: {min: 10, max: 20}}), remainingMessages: faker.number.int({min: 0}), ...overrideResponse})


export const getGetHealthMockHandler = (overrideResponse?: Health | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Health> | Health), options?: RequestHandlerOptions) => {
  return http.get('*/health', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetHealthResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetReadinessMockHandler = (overrideResponse?: Readiness | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Readiness> | Readiness), options?: RequestHandlerOptions) => {
  return http.get('*/health/ready', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetReadinessResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRegisterMockHandler = (overrideResponse?: AuthSession | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AuthSession> | AuthSession), options?: RequestHandlerOptions) => {
  return http.post('*/auth/register', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRegisterResponseMock(),
      { status: 201
      })
  }, options)
}

export const getLoginMockHandler = (overrideResponse?: AuthSession | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AuthSession> | AuthSession), options?: RequestHandlerOptions) => {
  return http.post('*/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getLoginResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRefreshTokensMockHandler = (overrideResponse?: AccessToken | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AccessToken> | AccessToken), options?: RequestHandlerOptions) => {
  return http.post('*/auth/refresh', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRefreshTokensResponseMock(),
      { status: 200
      })
  }, options)
}

export const getLogoutMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/auth/logout', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getGetMeMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/users/me', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateMeMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.patch('*/users/me', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateMeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListMyConsentsMockHandler = (overrideResponse?: ConsentList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ConsentList> | ConsentList), options?: RequestHandlerOptions) => {
  return http.get('*/users/me/consents', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListMyConsentsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getSetMyConsentMockHandler = (overrideResponse?: Consent | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Consent> | Consent), options?: RequestHandlerOptions) => {
  return http.put('*/users/me/consents/:purpose', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSetMyConsentResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListPatientsMockHandler = (overrideResponse?: PatientPage | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<PatientPage> | PatientPage), options?: RequestHandlerOptions) => {
  return http.get('*/patients', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListPatientsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreatePatientMockHandler = (overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Patient> | Patient), options?: RequestHandlerOptions) => {
  return http.post('*/patients', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreatePatientResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetPatientMockHandler = (overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Patient> | Patient), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPatientResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdatePatientMockHandler = (overrideResponse?: Patient | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Patient> | Patient), options?: RequestHandlerOptions) => {
  return http.patch('*/patients/:patientId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdatePatientResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListPatientConsentsMockHandler = (overrideResponse?: ConsentList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ConsentList> | ConsentList), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/consents', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListPatientConsentsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getSetPatientConsentMockHandler = (overrideResponse?: Consent | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Consent> | Consent), options?: RequestHandlerOptions) => {
  return http.put('*/patients/:patientId/consents/:purpose', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSetPatientConsentResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListPatientCaregiversMockHandler = (overrideResponse?: CareLinkPage | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<CareLinkPage> | CareLinkPage), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/caregivers', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListPatientCaregiversResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRevokePatientCaregiverMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/patients/:patientId/caregivers/:userId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getCreateCaregiverInvitationMockHandler = (overrideResponse?: CaregiverInvitation | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CaregiverInvitation> | CaregiverInvitation), options?: RequestHandlerOptions) => {
  return http.post('*/patients/:patientId/caregiver-invitations', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateCaregiverInvitationResponseMock(),
      { status: 201
      })
  }, options)
}

export const getAcceptCaregiverInvitationMockHandler = (overrideResponse?: CareLink | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CareLink> | CareLink), options?: RequestHandlerOptions) => {
  return http.post('*/caregiver-invitations/:code/accept', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAcceptCaregiverInvitationResponseMock(),
      { status: 201
      })
  }, options)
}

export const getCreatePairingCodeMockHandler = (overrideResponse?: PairingCode | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PairingCode> | PairingCode), options?: RequestHandlerOptions) => {
  return http.post('*/devices/pairing-codes', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreatePairingCodeResponseMock(),
      { status: 201
      })
  }, options)
}

export const getConfirmPairingCodeMockHandler = (overrideResponse?: Device | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Device> | Device), options?: RequestHandlerOptions) => {
  return http.post('*/devices/pairing-codes/:code/confirm', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getConfirmPairingCodeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getRequestDeviceTokenMockHandler = (overrideResponse?: TokenPair | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TokenPair> | TokenPair), options?: RequestHandlerOptions) => {
  return http.post('*/devices/token', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getRequestDeviceTokenResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetMyDeviceMockHandler = (overrideResponse?: Device | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Device> | Device), options?: RequestHandlerOptions) => {
  return http.get('*/devices/me', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMyDeviceResponseMock(),
      { status: 200
      })
  }, options)
}

export const getSetMyPushTokenMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.put('*/devices/me/push-token', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getListPatientDevicesMockHandler = (overrideResponse?: DevicePage | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DevicePage> | DevicePage), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/devices', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListPatientDevicesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUnpairDeviceMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/devices/:deviceId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getListMedicationsMockHandler = (overrideResponse?: MedicationPage | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MedicationPage> | MedicationPage), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/medications', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListMedicationsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateMedicationMockHandler = (overrideResponse?: Medication | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Medication> | Medication), options?: RequestHandlerOptions) => {
  return http.post('*/patients/:patientId/medications', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateMedicationResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetMedicationMockHandler = (overrideResponse?: Medication | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Medication> | Medication), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/medications/:medicationId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMedicationResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateMedicationMockHandler = (overrideResponse?: Medication | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Medication> | Medication), options?: RequestHandlerOptions) => {
  return http.patch('*/patients/:patientId/medications/:medicationId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateMedicationResponseMock(),
      { status: 200
      })
  }, options)
}

export const getArchiveMedicationMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/patients/:patientId/medications/:medicationId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getListSchedulesMockHandler = (overrideResponse?: ScheduleList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ScheduleList> | ScheduleList), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/medications/:medicationId/schedules', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListSchedulesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateScheduleMockHandler = (overrideResponse?: Schedule | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Schedule> | Schedule), options?: RequestHandlerOptions) => {
  return http.post('*/patients/:patientId/medications/:medicationId/schedules', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateScheduleResponseMock(),
      { status: 201
      })
  }, options)
}

export const getUpdateScheduleMockHandler = (overrideResponse?: Schedule | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<Schedule> | Schedule), options?: RequestHandlerOptions) => {
  return http.patch('*/patients/:patientId/medications/:medicationId/schedules/:scheduleId', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateScheduleResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteScheduleMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/patients/:patientId/medications/:medicationId/schedules/:scheduleId', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getGetMyPlanMockHandler = (overrideResponse?: Plan | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Plan> | Plan), options?: RequestHandlerOptions) => {
  return http.get('*/devices/me/plan', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMyPlanResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetPatientPlanMockHandler = (overrideResponse?: Plan | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Plan> | Plan), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/plan', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetPatientPlanResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateMyDoseEventsMockHandler = (overrideResponse?: DoseEventBatchResult | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<DoseEventBatchResult> | DoseEventBatchResult), options?: RequestHandlerOptions) => {
  return http.post('*/devices/me/dose-events', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateMyDoseEventsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getListDoseHistoryMockHandler = (overrideResponse?: DoseHistoryPage | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<DoseHistoryPage> | DoseHistoryPage), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/dose-history', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListDoseHistoryResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetAdherenceMockHandler = (overrideResponse?: Adherence | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Adherence> | Adherence), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/adherence', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAdherenceResponseMock(),
      { status: 200
      })
  }, options)
}

export const getVerifyEmailMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/auth/verify-email', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getResendVerificationMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/auth/resend-verification', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 202
      })
  }, options)
}

export const getForgotPasswordMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/auth/forgot-password', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 202
      })
  }, options)
}

export const getResetPasswordMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/auth/reset-password', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getListMyNotificationChannelsMockHandler = (overrideResponse?: NotificationChannelList | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NotificationChannelList> | NotificationChannelList), options?: RequestHandlerOptions) => {
  return http.get('*/users/me/notification-channels', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListMyNotificationChannelsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateTelegramLinkMockHandler = (overrideResponse?: TelegramLink | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<TelegramLink> | TelegramLink), options?: RequestHandlerOptions) => {
  return http.post('*/users/me/notification-channels/telegram/link', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateTelegramLinkResponseMock(),
      { status: 201
      })
  }, options)
}

export const getUnlinkTelegramMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/users/me/notification-channels/telegram', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}

export const getGetMyNotificationPreferencesMockHandler = (overrideResponse?: NotificationPreferences | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<NotificationPreferences> | NotificationPreferences), options?: RequestHandlerOptions) => {
  return http.get('*/users/me/notification-preferences', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetMyNotificationPreferencesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getSetMyNotificationPreferencesMockHandler = (overrideResponse?: NotificationPreferences | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<NotificationPreferences> | NotificationPreferences), options?: RequestHandlerOptions) => {
  return http.put('*/users/me/notification-preferences', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSetMyNotificationPreferencesResponseMock(),
      { status: 200
      })
  }, options)
}

export const getTelegramWebhookMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/telegram/webhook', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getListReportsMockHandler = (overrideResponse?: ReportPage | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReportPage> | ReportPage), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/reports', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListReportsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateReportMockHandler = (overrideResponse?: Report | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Report> | Report), options?: RequestHandlerOptions) => {
  return http.post('*/patients/:patientId/reports', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateReportResponseMock(),
      { status: 202
      })
  }, options)
}

export const getGetReportMockHandler = (overrideResponse?: Report | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Report> | Report), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/reports/:reportId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetReportResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDownloadReportPdfMockHandler = (overrideResponse?: Blob | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Blob> | Blob), options?: RequestHandlerOptions) => {
  return http.get('*/patients/:patientId/reports/:reportId/pdf', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {

  const binaryBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDownloadReportPdfResponseMock();
    return new HttpResponse(binaryBody,
      { status: 200,
        headers: { 'Content-Type': 'application/pdf' }
      })
  }, options)
}

export const getSendChatMessageMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.post('*/patients/:patientId/chat/messages', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {

  const resolvedBody = overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSendChatMessageResponseMock();
    const textBody = typeof resolvedBody === 'string' ? resolvedBody : JSON.stringify(resolvedBody ?? null);
    return HttpResponse.text(textBody,
      { status: 200, headers: { 'Content-Type': 'text/event-stream' }
      })
  }, options)
}

export const getSendMyChatMessageMockHandler = (overrideResponse?: WatchChatReply | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<WatchChatReply> | WatchChatReply), options?: RequestHandlerOptions) => {
  return http.post('*/devices/me/chat/messages', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSendMyChatMessageResponseMock(),
      { status: 200
      })
  }, options)
}
export const getAPIDeRecordatoriosDeMedicamentosMock = () => [
  getGetHealthMockHandler(),
  getGetReadinessMockHandler(),
  getRegisterMockHandler(),
  getLoginMockHandler(),
  getRefreshTokensMockHandler(),
  getLogoutMockHandler(),
  getGetMeMockHandler(),
  getUpdateMeMockHandler(),
  getListMyConsentsMockHandler(),
  getSetMyConsentMockHandler(),
  getListPatientsMockHandler(),
  getCreatePatientMockHandler(),
  getGetPatientMockHandler(),
  getUpdatePatientMockHandler(),
  getListPatientConsentsMockHandler(),
  getSetPatientConsentMockHandler(),
  getListPatientCaregiversMockHandler(),
  getRevokePatientCaregiverMockHandler(),
  getCreateCaregiverInvitationMockHandler(),
  getAcceptCaregiverInvitationMockHandler(),
  getCreatePairingCodeMockHandler(),
  getConfirmPairingCodeMockHandler(),
  getRequestDeviceTokenMockHandler(),
  getGetMyDeviceMockHandler(),
  getSetMyPushTokenMockHandler(),
  getListPatientDevicesMockHandler(),
  getUnpairDeviceMockHandler(),
  getListMedicationsMockHandler(),
  getCreateMedicationMockHandler(),
  getGetMedicationMockHandler(),
  getUpdateMedicationMockHandler(),
  getArchiveMedicationMockHandler(),
  getListSchedulesMockHandler(),
  getCreateScheduleMockHandler(),
  getUpdateScheduleMockHandler(),
  getDeleteScheduleMockHandler(),
  getGetMyPlanMockHandler(),
  getGetPatientPlanMockHandler(),
  getCreateMyDoseEventsMockHandler(),
  getListDoseHistoryMockHandler(),
  getGetAdherenceMockHandler(),
  getVerifyEmailMockHandler(),
  getResendVerificationMockHandler(),
  getForgotPasswordMockHandler(),
  getResetPasswordMockHandler(),
  getListMyNotificationChannelsMockHandler(),
  getCreateTelegramLinkMockHandler(),
  getUnlinkTelegramMockHandler(),
  getGetMyNotificationPreferencesMockHandler(),
  getSetMyNotificationPreferencesMockHandler(),
  getTelegramWebhookMockHandler(),
  getListReportsMockHandler(),
  getCreateReportMockHandler(),
  getGetReportMockHandler(),
  getDownloadReportPdfMockHandler(),
  getSendChatMessageMockHandler(),
  getSendMyChatMessageMockHandler()
]
